name: Deploy Automatico su VHosting (SFTP)

on:
  push:
    branches:
      - main # Cambia in 'master' se il tuo ramo si chiama master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Caricamento file via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: '/home/sitiit1/public_html/Testgoogleai/'